### ISSUE TITLE
Vex conversion mechanic

### ISSUE THREAD

**Issue by giggity404** [2mal3/Allay-in-a-Bottle#11]
As I suggested on the vex bottling issue, it'd be a useful feature to add a vex to allay conversion mechanic. I think ideally we'd keep the mechanic similar to villager conversion so it feels familiar to ppl: splash potion of something with precious item (golden carrot or melon maybe) the main issue is vex's go through blocks & are hard to keep still, so I'd suggested making a vex conversion station where they're held in place. My idea was an electric chair type situation haha. as you can see below. All we'd have to do is a block check when placing the vex down, see if a lightning rod is on its sides, then any copper blocks, then powered redstone lamps, then the conversion mechanic is simpler to implement if the vex is held still.

Let me know what you think of the idea. I've experimented with some parts of this already, I'll commit them to my VexConversion fork when I can

![image](https://user-images.githubusercontent.com/54961025/203945643-d3d5c347-2ace-4b9e-82be-78807ad282ad.png)

**Comment by 2mal3** [comment]
I think it's actually a good idea, but for me, it moves too far away from the basic idea of the datapack.

However, there's nothing wrong with making a separate datapack for it if you want.
