### ISSUE TITLE
Noteblock pairing

### ISSUE THREAD

**Issue by giggity404** [2mal3/Allay-in-a-Bottle#13]
A feature that I got working for personal use, but I think it'd be a godsend for anyone who's tried to make allay based farm collection systems or allay item filters. Pairing the allays to their noteblock is extremely tedious and if it breaks it's a nightmare to re-sync them as they all get jumbled up. With this you can just catch them and link them. The code is also surprisingly simple. 
I used [xokz Allay Noteblock Line Link Visualizer](https://www.planetminecraft.com/data-pack/allay-noteblock-link-visualizer/) to trace the noteblock the allay is linked to.

Also I won't indefinitely be trying to add features, I swear this is the last thing :) 

![notelbockpairing](https://user-images.githubusercontent.com/54961025/206860695-0e096f8d-8a4e-4735-a9c9-3770e39fa5d4.gif)

**Comment by 2mal3** [comment]
Good idea! You are also welcome to continue to make suggestions :D
