### ISSUE TITLE
Spam in the console

### ISSUE THREAD

**Issue by Vyacheslav73195** [2mal3/Allay-in-a-Bottle#16]
### Minecraft version

1.20.1

### Datapack version

v2.1.0

### Expected Behavior

It should work

### Actual Behavior

Spam in the console:
[22:37:33 WARN]: Unable to add mob to team "aiab.no_collision" (that team probably doesn't exist)

### Reproduction Steps

Click on allay

**Comment by 2mal3** [comment]
Hi! Strange, that does not happen to me, but should be easy to fix. Just reinstall the datapack (i.e. with `/function aiab:core/uninstall`)

**Comment by Vyacheslav73195** [comment]
This does not help, I installed the datapack on the test and main server and this error occurred on two of them. Paper #169

**Comment by 2mal3** [comment]
I am sorry, but for technical reasons the datapack cannot support Paper (or Spigot, Bukkit). Such servers are meant for plugins and datapacks generally don't run well on them.
