### ISSUE TITLE
Majority air blocks need to be considered air (but i cant get it to work)

### ISSUE THREAD

**Issue by giggity404** [2mal3/Allay-in-a-Bottle#8]
I forgot to include it as part of my code, but to place allays in a minecart that's sitting on a rail, rails need to be considered an air block, which they essentially are. However, I couldn't get block families to work in the blocks JSON part. This should technically work, but it doesn't seem to. When testing I had listed out all the rail types, but that's not ideal, as there's other majority air blocks that should be ignored like flowers, buttons, etc. I'm not sure if I'm missing some mcbuild syntax or something like that
```
blocks air {
  minecraft:air
  minecraft:cave_air
  #minecraft:rails
}
```

**Comment by 2mal3** [comment]
Yeah, mc-build is a bit weird about that, but if you put a `\` in front of the `#` (e.g. `\#minecraft:rails`), it should work.

However, I would not remove the rails. In my tests, placing the Allays in Minecarts worked better with it.
